import tShirt1 from '../src/public/img/tshirt/tshirt1.jpg'
var tShirt = [
    { 
      price: 249.99,
      isNew:true,
      img: tShirt1,
      img2: '/img/tshirt/tshirt2.jpg',
      img3: '/img/tshirt/tshirt2.jpg',
      img4: '/img/tshirt/tshirt2.jpg',
      img5: '/img/tshirt/tshirt2.jpg',
      title: 'HolaaAAA azul',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '0',
      size:  ['x', 'l'],
      id: 1
    },
    { 
      price: 329.99,
      isNew:true,
      img: '/img/tshirt/tshirt2.jpg',
      img2: '/img/tshirt/tshirt1.jpg',
      img3: '/img/tshirt/tshirt1.jpg',
      img4: '/img/tshirt/tshirt1.jpg',
      img5: '/img/tshirt/tshirt1.jpg',
      title: 'Camisa 2 azul',
      genero: 'mujeres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '0',
      size:  ['x', 'l'],
      id: 2
    },
    { 
      price: 100,
      isNew:true,
      img: '/img/tshirt/tshirt3.jpg',
      img2: '/img/tshirt/tshirt2.jpg',
      img3: '/img/tshirt/tshirt2.jpg',
      img4: '/img/tshirt/tshirt2.jpg',
      img5: '/img/tshirt/tshirt2.jpg',
      title: 'Camisa 3',
      genero: 'hombres',
      type: 'destacados',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType:'0' ,
      size:  ['x', 'l'],
      id: 3
    },
    { 
      price: 200,
      isNew:true,
      img: '/img/tshirt/tshirt4.jpg',
      img2: '/img/tshirt/tshirt2.jpg',
      img3: '/img/tshirt/tshirt2.jpg',
      img4: '/img/tshirt/tshirt2.jpg',
      img5: '/img/tshirt/tshirt2.jpg',
      title: 'Camisa 4',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '0',
      size:  ['x', 'l'],
      id: 4
    },
    { 
      price: 450,
      isNew:true,
      img: '/img/tshirt/tshirt5.jpg',
      img2: '/img/tshirt/tshirt2.jpg',
      img3: '/img/tshirt/tshirt2.jpg',
      img4: '/img/tshirt/tshirt2.jpg',
      img5: '/img/tshirt/tshirt2.jpg',
      title: 'Camisa 5',
      genero: 'hombres',
      type: 'destacados',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '0',
      size:  ['x', 'l'],
      id: 5
    },
  ];



var Pants = [
    { 
      price: 80,
      isNew:true,
      img: '/img/pants/pant1.jpg',
      img2: '/img/pants/pant3.jpg',
      img3: '/img/pants/pant3.jpg',
      img4: '/img/pants/pant3.jpg',
      img5: '/img/pants/pant3.jpg',
      title: 'Pantalon 1 azul',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '1',
      size:  ['x', 'l'],
      id: 6
    },
    { 
      price: 270,
      isNew:true,
      img: '/img/pants/pant2.jpg',
      img2: '/img/pants/pant3.jpg',
      img3: '/img/pants/pant3.jpg',
      img4: '/img/pants/pant3.jpg',
      img5: '/img/pants/pant3.jpg',
      title: 'Pantalon 2 azul',
      genero: 'mujeres',
      type: 'destacados',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '1',
      size:  ['x', 'l'],
      id: 7
    },
    { 
      price: 360,
      isNew:true,
      img: '/img/pants/pant3.jpg',
      img2: '/img/pants/pant2.jpg',
      img3: '/img/pants/pant2.jpg',
      img4: '/img/pants/pant2.jpg',
      img5: '/img/pants/pant2.jpg',
      title: 'Pantalon 3',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '1',
      size:  ['x', 'l'],
      id: 8
    },
    { 
      price: 410,
      isNew:true,
      img: '/img/pants/pant4.jpg',
      img2: '/img/pants/pant2.jpg',
      img3: '/img/pants/pant2.jpg',
      img4: '/img/pants/pant2.jpg',
      img5: '/img/pants/pant2.jpg',
      title: 'Pantalon 4',
      genero: 'hombres',
      type: 'destacados',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '1',
      size:  ['x', 'l'],
      id: 9
    },
    { 
      price: 380,
      isNew:true,
      img: '/img/pants/pant5.jpg',
      img2: '/img/pants/pant2.jpg',
      img3: '/img/pants/pant2.jpg',
      img4: '/img/pants/pant2.jpg',
      img5: '/img/pants/pant2.jpg',
      title: 'Pantalon 5',
      genero: 'hombres',
      type: 'destacados',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '1',
      size:  ['x', 'l'],
      id: 10
    },
  ];



var Accesories = [
    { 
      price: 230,
      isNew:true,
      img: '/img/accesories/acc1.jpg',
      img2: '/img/accesories/acc2.jpg',
      img3: '/img/accesories/acc2.jpg',
      img4: '/img/accesories/acc2.jpg',
      img5: '/img/accesories/acc2.jpg',
      title: 'Accesorio 1 azul',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '3',
      size:  ['x', 'l'],
      id: 11
    },
    { 
      price: 180,
      isNew:true,
      img: '/img/accesories/acc2.jpg',
      img2: '/img/accesories/acc3.jpg',
      img3: '/img/accesories/acc3.jpg',
      img4: '/img/accesories/acc3.jpg',
      img5: '/img/accesories/acc3.jpg',
      title: 'Accesorio 2',
      genero: 'mujeres',
      type: 'destacados',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '3',
      size:  ['x', 'l'],
      id: 12
    },
    { 
      price: 470,
      isNew:true,
      img: '/img/accesories/acc3.jpg',
      img2: '/img/accesories/acc2.jpg',
      img3: '/img/accesories/acc2.jpg',
      img4: '/img/accesories/acc2.jpg',
      img5: '/img/accesories/acc2.jpg',
      title: 'Accesorio 3 azul',
      genero: 'mujeres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '3',
      size:  ['x', 'l'],
      id: 13
    },
    { 
      price: 99,
      isNew:true,
      img: '/img/accesories/acc4.jpg',
      img2: '/img/accesories/acc2.jpg',
      img3: '/img/accesories/acc2.jpg',
      img4: '/img/accesories/acc2.jpg',
      img5: '/img/accesories/acc2.jpg',
      title: 'Accesorio 4',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '3',
      size:  ['x', 'l'],
      id: 14
    },
    { 
      price: 39.99,
      isNew:true,
      img: '/img/accesories/acc5.jpg',
      img2: '/img/accesories/acc2.jpg',
      img3: '/img/accesories/acc2.jpg',
      img4: '/img/accesories/acc2.jpg',
      img5: '/img/accesories/acc2.jpg',
      title: 'Accesorio 5',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '3',
      size:  ['x', 'l'],
      id: 15
    },
  ];


var hoodies = [
    { 
      price: 500,
      isNew:true,
      img: '/img/hoodie/hoodie1.jpg',
      img2: '/img/hoodie/hoodie2.jpg',
      img3: '/img/hoodie/hoodie2.jpg',
      img4: '/img/hoodie/hoodie2.jpg',
      img5: '/img/hoodie/hoodie2.jpg',
      title: 'Hoodie 1 azul',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '2',
      size:  ['x', 'l'],
      id: 16
    },
    { 
      price: 380,
      isNew:true,
      img: '/img/hoodie/hoodie2.jpg',
      img2: '/img/hoodie/hoodie1.jpg',
      img3: '/img/hoodie/hoodie1.jpg',
      img4: '/img/hoodie/hoodie1.jpg',
      img5: '/img/hoodie/hoodie1.jpg',
      title: 'Hoodie 2',
      genero: 'mujeres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '2',
      size:  ['x', 'l'],
      id: 17
    },
    { 
      price: 260,
      isNew:true,
      img: '/img/hoodie/hoodie3.jpg',
      img2: '/img/hoodie/hoodie2.jpg',
      img3: '/img/hoodie/hoodie2.jpg',
      img4: '/img/hoodie/hoodie2.jpg',
      img5: '/img/hoodie/hoodie2.jpg',
      title: 'Hoodie 3',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '2',
      size:  ['x', 'l'],
      id: 18
    },
    { 
      price: 189,
      isNew:true,
      img: '/img/hoodie/hoodie4.jpg',
      img2: '/img/hoodie/hoodie2.jpg',
      img3: '/img/hoodie/hoodie2.jpg',
      img4: '/img/hoodie/hoodie2.jpg',
      img5: '/img/hoodie/hoodie2.jpg',
      title: 'Hoodie 4',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '2',
      size:  ['x', 'l'],
      id: 19
    },
    { 
      price: 375,
      isNew:true,
      img: '/img/hoodie/hoodie5.jpg',
      img2: '/img/hoodie/hoodie2.jpg',
      img3: '/img/hoodie/hoodie2.jpg',
      img4: '/img/hoodie/hoodie2.jpg',
      img5: '/img/hoodie/hoodie2.jpg',
      title: 'Hoodie 5',
      genero: 'hombres',
      type: 'top ventas',
      desc: 'hsodfskldfjskldjfkjsdfj',
      catType: '2',
      size:  ['x', 'l'],
      id: 20
    },
  ];


  export {tShirt, hoodies, Accesories, Pants}

